ifeq ($(CONFIG_ARCH_KALAMA), y)

ifeq ($(SOMC_PLATFORM), yodo)
SOMC_PRODUCT_OPERATOR = $(SOMC_TARGET_PRODUCT)_$(SOMC_TARGET_OPERATOR)

ifeq ($(SOMC_PRODUCT_OPERATOR),pdx234_generic)
dtbo-y += kalama-audio.dtbo \
	          somc-yodo-audio-pdx234.dtbo
endif

ifeq ($(SOMC_PRODUCT_OPERATOR),pdx237_generic)
dtbo-y += kalama-audio.dtbo \
	          somc-yodo-audio-pdx237.dtbo
endif

else
dtbo-y += kalama-audio.dtbo \
                 kalama-audio-cdp.dtbo \
                 kalama-audio-cdp-nfc.dtbo \
                 kalama-audio-wsa883x-cdp.dtbo \
                 kalama-audio-mtp.dtbo \
                 kalama-audio-mtp-nfc.dtbo \
                 kalama-audio-qrd.dtbo \
                 kalama-audio-atp.dtbo \
                 kalama-audio-rcm.dtbo \
                 kalama-audio-rumi.dtbo \
                 kalama-audio-hdk.dtbo \
                 kalama-sg-audio-hhg.dtbo
endif
endif

 always-y    := $(dtb-y) $(dtbo-y)
 subdir-y    := $(dts-dirs)
 clean-files    := *.dtb *.dtbo
