ifeq ($(CONFIG_ARCH_SUN),y)
dtbo-y += nxp/sun-nfc.dtbo \
          nxp/sun-nfc-cdp.dtbo \
          nxp/sun-nfc-mtp.dtbo \
          nxp/sun-nfc-qrd-sku2-v8.dtbo \
          nxp/sun-nfc-qrd.dtbo \
          nxp/tuna-nfc.dtbo \
          nxp/kera-nfc.dtbo

endif

ifeq ($(CONFIG_ARCH_PARROT),y)
dtbo-y += nxp/parrot-nfc.dtbo \
          nxp/parrot-nfc-qrd.dtbo \
          nxp/parrot-nfc-idp.dtbo \
          nxp/parrot-nfc-atp.dtbo \
          nxp/parrot-nfc-idp-wcn6755.dtbo \
          nxp/parrot-nfc-idp-wcn3990-amoled-rcm.dtbo
endif

ifeq ($(CONFIG_ARCH_RAVELIN),y)
dtbo-y += nxp/ravelin-nfc.dtbo \
          nxp/ravelin-nfc-qrd.dtbo \
          nxp/ravelin-nfc-idp.dtbo \
          nxp/ravelin-nfc-atp.dtbo
endif


always-y        := $(dtb-y) $(dtbo-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtb *.dtbo


